#---------------------------------------------------------------------
# GitHub Action Workflow to Deploy AWS-CLOUD-RESUME-AILVES App to AWS S3
#
# Version      Date        Info
# 1.0          2024        Initial Version
#
# Made by Aleksandr Ilves Copyleft (c) 2024
#---------------------------------------------------------------------
    name: Deploy to S3 and Invalidate CloudFront
    env:
      S3_BUCKET_NAME : "aws-cloud-resume-ailves-dev-destination"
      AWS_REGION_NAME: "us-east-2"
    
    on:
      push:
        branches:
        - main
    
    jobs:
      deploy:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
    
        - name: Deploy to S3
          uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: ${{ env.S3_BUCKET_NAME }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
            AWS_REGION: ${{ env.AWS_REGION_NAME }}  # optional: defaults to us-east-2
            SOURCE_DIR: 'public'  # optional: defaults to entire repository
            